twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        'assets/images': images
        'assets/css': styles
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']